"""Local image post-processing utilities.

Active in current runtime:
  * ``inject_exif_only`` — writes AI-transparency EXIF (Art. 50 compliance).
  * ``crop_to_aspect`` — head-biased crop for document-style targets.
  * ``upscale_lanczos`` — integer-factor PIL LANCZOS upscale for large-face portraits.

Reve REST ``/v1/image/edit`` does not accept ``aspect_ratio`` and does not
expose a post-processing pipeline, so cropping and upscaling are done
locally via PIL.
"""

from __future__ import annotations

import io
import logging
import struct
from datetime import datetime, timezone

from PIL import Image

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# EXIF metadata injection (AI transparency, EU AI Act Art. 50 / GDPR)
# ---------------------------------------------------------------------------

AI_TRANSPARENCY_MAKE = "AI Look Studio"
AI_TRANSPARENCY_MODEL = "AI-generated (VLM pipeline)"
AI_TRANSPARENCY_COMMENT = (
    "AI-generated by AI Look Studio. "
    "This image was synthesised by generative AI and does not depict an "
    "unedited photograph. EU AI Act Art. 50 / GDPR transparency notice."
)


def _build_minimal_exif(dt: datetime | None = None) -> bytes:
    """Build an EXIF APP1 segment advertising AI-generated origin.

    Uses ``piexif`` when available (produces a standards-compliant TIFF
    IFD), with a best-effort raw byte fallback so the pipeline never
    breaks if the dependency is missing.
    """
    if dt is None:
        dt = datetime.now(timezone.utc)

    dt_str_bytes = dt.strftime("%Y:%m:%d %H:%M:%S").encode("ascii")

    try:
        import piexif  # type: ignore
        import piexif.helper  # type: ignore

        user_comment = piexif.helper.UserComment.dump(
            AI_TRANSPARENCY_COMMENT, encoding="unicode"
        )
        exif_dict = {
            "0th": {
                piexif.ImageIFD.Make: AI_TRANSPARENCY_MAKE.encode("ascii"),
                piexif.ImageIFD.Model: AI_TRANSPARENCY_MODEL.encode("ascii"),
                piexif.ImageIFD.Software: AI_TRANSPARENCY_MAKE.encode("ascii"),
                piexif.ImageIFD.DateTime: dt_str_bytes,
                piexif.ImageIFD.ImageDescription: b"AI-generated content",
            },
            "Exif": {
                piexif.ExifIFD.UserComment: user_comment,
                piexif.ExifIFD.DateTimeOriginal: dt_str_bytes,
                piexif.ExifIFD.DateTimeDigitized: dt_str_bytes,
            },
        }
        exif_tiff = piexif.dump(exif_dict)
        return b"\xff\xe1" + struct.pack(">H", len(exif_tiff) + 2) + exif_tiff
    except Exception:
        logger.debug("piexif EXIF build failed, falling back to raw", exc_info=True)

    make = AI_TRANSPARENCY_MAKE.encode("ascii") + b"\x00"
    model = AI_TRANSPARENCY_MODEL.encode("ascii") + b"\x00"
    dt_str = dt_str_bytes + b"\x00"

    def _string_offset(tag: int, s: bytes, offset: int) -> tuple[bytes, bytes]:
        entry = struct.pack(">HHI", tag, 2, len(s)) + struct.pack(">I", offset)
        return entry, s

    header = b"Exif\x00\x00MM"
    header += struct.pack(">HI", 42, 8)

    try:
        entries: list[bytes] = []
        extra_data = b""
        num_tags = 3
        ifd_start = 8
        ifd_size = 2 + num_tags * 12 + 4
        data_offset = ifd_start + ifd_size

        e1, d1 = _string_offset(0x010F, make, data_offset)
        entries.append(e1)
        extra_data += d1
        data_offset += len(d1)

        e2, d2 = _string_offset(0x0110, model, data_offset)
        entries.append(e2)
        extra_data += d2
        data_offset += len(d2)

        e3, d3 = _string_offset(0x0132, dt_str, data_offset)
        entries.append(e3)
        extra_data += d3

        ifd = struct.pack(">H", num_tags)
        for e in entries:
            ifd += e
        ifd += struct.pack(">I", 0)

        tiff_body = header + ifd + extra_data
        app1 = b"\xff\xe1" + struct.pack(">H", len(tiff_body) + 2) + tiff_body
        return app1
    except Exception:
        logger.debug("EXIF construction failed, skipping")
        return b""


def _inject_exif(jpeg_bytes: bytes) -> bytes:
    """Inject minimal EXIF into JPEG bytes, replacing any existing APP1."""
    exif_segment = _build_minimal_exif()
    if not exif_segment:
        return jpeg_bytes
    if jpeg_bytes[:2] != b"\xff\xd8":
        return jpeg_bytes

    pos = 2
    while pos < len(jpeg_bytes) - 1:
        if jpeg_bytes[pos] != 0xFF:
            break
        marker = jpeg_bytes[pos + 1]
        if marker == 0xE1:
            seg_len = struct.unpack(">H", jpeg_bytes[pos + 2 : pos + 4])[0]
            return jpeg_bytes[:2] + exif_segment + jpeg_bytes[pos + 2 + seg_len :]
        if marker in (0xDA, 0x00):
            break
        if pos + 3 < len(jpeg_bytes):
            seg_len = struct.unpack(">H", jpeg_bytes[pos + 2 : pos + 4])[0]
            pos += 2 + seg_len
        else:
            break

    return jpeg_bytes[:2] + exif_segment + jpeg_bytes[2:]


def inject_exif_only(image_bytes: bytes) -> bytes:
    """Inject EXIF metadata into image bytes without any other processing."""
    try:
        return _inject_exif(image_bytes)
    except Exception:
        return image_bytes


# ---------------------------------------------------------------------------
# Local aspect-ratio crop and upscale
# ---------------------------------------------------------------------------


def _parse_aspect_ratio(target_ar: str) -> tuple[int, int] | None:
    """Accept '3:4', '16:9', '1:1' etc. Return (w, h) or None if invalid."""
    if not target_ar or ":" not in target_ar:
        return None
    try:
        w_str, h_str = target_ar.split(":", 1)
        w = int(w_str.strip())
        h = int(h_str.strip())
    except ValueError:
        return None
    if w <= 0 or h <= 0:
        return None
    return w, h


def crop_to_aspect(image_bytes: bytes, target_ar: str) -> bytes:
    """Crop the image to ``target_ar`` (e.g. '3:4', '2:3', '7:9', '1:1').

    Uses a head-biased crop: horizontally centred, vertically anchored
    to the upper 45% so the face — almost always in the upper third of
    portraits — is preserved. Re-encodes to PNG to avoid a double JPEG
    compression. Returns original bytes if input is malformed or the
    aspect ratio string is invalid.
    """
    ratio = _parse_aspect_ratio(target_ar)
    if ratio is None:
        return image_bytes
    tw, th = ratio

    try:
        img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    except Exception:
        logger.debug("crop_to_aspect: input is not a valid image, returning as-is")
        return image_bytes

    w, h = img.size
    if w <= 0 or h <= 0:
        return image_bytes

    current_ar = w / h
    target_aspect = tw / th

    if abs(current_ar - target_aspect) < 1e-3:
        return image_bytes

    if current_ar > target_aspect:
        new_w = int(round(h * target_aspect))
        new_w = max(1, min(new_w, w))
        x0 = (w - new_w) // 2
        box = (x0, 0, x0 + new_w, h)
    else:
        new_h = int(round(w / target_aspect))
        new_h = max(1, min(new_h, h))
        y0 = int(round((h - new_h) * 0.45))
        y0 = max(0, min(y0, h - new_h))
        box = (0, y0, w, y0 + new_h)

    cropped = img.crop(box)
    buf = io.BytesIO()
    cropped.save(buf, format="PNG", optimize=False)
    return buf.getvalue()


def upscale_lanczos(image_bytes: bytes, factor: int = 2) -> bytes:
    """Upscale the image by an integer factor using PIL LANCZOS resampling.

    Used after Reve generation when the detected face area is large
    enough that a native 1024px crop would deliver an under-detailed
    headshot. Re-encodes to PNG. Returns the original bytes on any
    failure so the pipeline never stalls on post-processing.
    """
    if factor is None or int(factor) <= 1:
        return image_bytes
    factor = int(factor)

    try:
        img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    except Exception:
        logger.debug("upscale_lanczos: input is not a valid image, returning as-is")
        return image_bytes

    w, h = img.size
    if w <= 0 or h <= 0:
        return image_bytes

    upscaled = img.resize((w * factor, h * factor), Image.LANCZOS)
    buf = io.BytesIO()
    upscaled.save(buf, format="PNG", optimize=False)
    return buf.getvalue()
